# .github/workflows/deploy.yml
name: Deploy using Google Cloud Run ()
on:
  push:
    branches:
      - master
jobs:
  # publish:
  #   if: ${{contains(github.event.head_commit.message, '[build]')}}
  deploy:
    name: Deploying flask app
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy-now]')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json : ${{ secrets.GCP_SA_KEY_JSON }}

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '383.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          # service_account_email: "github-actions@mldeployflask.iam.gserviceaccount.com"
          project_id: ${{ secrets.GCP_PROJECT_ID}}

      - name: Building ()
        run: |-
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.APP_ID }}

      # Setup gcloud CLI
      - name: Deploy ()
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ secrets.APP_ID }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.APP_ID }}
          region: us-east1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID}}