# .github/workflows/deploy.yml
name: Deploy using Google Cloud Run ()
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying flask app
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'to deploy')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          # service_account_email: "github-actions@mldeployflask.iam.gserviceaccount.com"
          project_id: ${{ secrets.GCP_PROJECT_ID}}

      - name: Building ()
        run: |-
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.APP_ID }}

      # Setup gcloud CLI
      - name: Deploy ()
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ secrets.APP_ID }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.APP_ID }}
          region: us-east1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID}}